# ============================================================
# Secret Backend — Credentials Spring Boot
# Valeurs extraites exactement de votre Dockerfile.backend
# et docker-compose.yml
#
# Vérification :
#   echo "cGVha2ZpdA==" | base64 -d        → peakfit
#   echo "cGVha2ZpdDEyMw==" | base64 -d    → peakfit123
#   echo "UGVha0Yxd..." | base64 -d        → PeakF1t@2026#SecureKey$MySQL!XyZ9qRst
# ============================================================
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: peakfit
  labels:
    app: backend
    project: peakfit
type: Opaque
data:
  # echo -n "peakfit" | base64
  DB_USERNAME: cGVha2ZpdA==

  # echo -n "peakfit123" | base64
  DB_PASSWORD: cGVha2ZpdDEyMw==

  # echo -n "PeakF1t@2026#SecureKey$MySQL!XyZ9qRst" | base64
  JWT_SECRET: UGVha0YxdEAyMDI2I1NlY3VyZUtleUBNeVNRTCFYeVo5cVJzdA==

  # echo -n "604800000" | base64
  JWT_EXPIRATION: NjA0ODAwMDAwMA==
