# Stage 1 — Build React
FROM node:18-alpine AS builder
WORKDIR /app
COPY frontend/package.json ./
RUN npm install --silent
COPY frontend/public ./public
COPY frontend/src    ./src
ARG REACT_APP_API_URL=/api
ENV REACT_APP_API_URL=$REACT_APP_API_URL
RUN npm run build

# Stage 2 — Nginx avec proxy vers backend
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
# Copier le fichier nginx.conf depuis le contexte de build
COPY nginx-k8s.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
