FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline -q
COPY src ./src
RUN mvn package -DskipTests -q

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
EXPOSE 8091

# MySQL — correspond exactement à application.properties
ENV SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/peakfit?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
ENV SPRING_DATASOURCE_USERNAME=peakfit
ENV SPRING_DATASOURCE_PASSWORD=peakfit123
ENV SERVER_PORT=8091
ENV JWT_SECRET=PeakF1t@2026#SecureKey$MySQL!XyZ9qRst
ENV JWT_EXPIRATION=604800000

ENTRYPOINT ["java","-XX:+UseContainerSupport","-XX:MaxRAMPercentage=75.0","-jar","app.jar"]
