---
- name: Installer Python3 d'abord
  hosts: web
  become: yes
  gather_facts: no
  tasks:
    - name: Installer python3
      raw: yum install -y python3
      changed_when: false

- name: Déployer PeakFit sur EC2
  hosts: web
  become: yes

  tasks:

    - name: Installer Docker
      yum:
        name: docker
        state: present

    - name: Démarrer Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Ajouter ec2-user au groupe docker
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Installer Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: "0755"

    - name: Lien symbolique docker-compose
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link

    - name: Créer dossier /opt/peakfit
      file:
        path: /opt/peakfit
        state: directory
        owner: ec2-user
        mode: "0755"

    - name: Copier docker-compose.yml
      copy:
        src: docker-compose.yml
        dest: /opt/peakfit/docker-compose.yml
        owner: ec2-user

    - name: Copier nginx.conf
      copy:
        src: nginx.conf
        dest: /opt/peakfit/nginx.conf
        owner: ec2-user

    - name: Copier image backend
      copy:
        src: backend.tar
        dest: /opt/peakfit/backend.tar
        owner: ec2-user

    - name: Copier image frontend
      copy:
        src: frontend.tar
        dest: /opt/peakfit/frontend.tar
        owner: ec2-user

    - name: Charger image backend
      command: docker load -i /opt/peakfit/backend.tar

    - name: Charger image frontend
      command: docker load -i /opt/peakfit/frontend.tar

    - name: Arrêter anciens containers
      command: /usr/local/bin/docker-compose down
      args:
        chdir: /opt/peakfit
      ignore_errors: yes

    - name: Lancer PeakFit
      command: /usr/local/bin/docker-compose up -d
      args:
        chdir: /opt/peakfit

    - name: Vérifier containers
      command: docker ps
      register: result

    - name: Afficher containers
      debug:
        var: result.stdout_lines
