server {
    listen 80;
    server_name _;

    # Health check pour le Load Balancer
    location /health {
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }

    # API Java → backend:8091
    location /api/ {
        proxy_pass http://backend:8091;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Frontend React → frontend:3000
    location / {
        proxy_pass http://frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
