name: PeakFit CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Backend
        run: |
          docker build \
            -f peakFit/Dockerfile.backend \
            -t peakfit-backend:latest \
            peakFit/

      - name: Build Frontend
        run: |
          docker build \
            -f peakFit/Dockerfile.frontend \
            -t peakfit-frontend:latest \
            peakFit/

      - name: Sauvegarder images
        run: |
          docker save peakfit-backend:latest  -o backend.tar
          docker save peakfit-frontend:latest -o frontend.tar

      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: docker-images
          path: "*.tar"
          retention-days: 1

  deploy:
    name: Deploy with Ansible
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download images
        uses: actions/download-artifact@v4
        with:
          name: docker-images
          path: ansible/

      - name: Installer Ansible
        run: sudo apt update && sudo apt install -y ansible

      - name: Configurer clé SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" | sed 's/\\n/\n/g' > ~/.ssh/peakfit-key.pem
          chmod 600 ~/.ssh/peakfit-key.pem

      - name: Mettre à jour inventory avec chemin absolu
        run: |
          sed -i "s|peakfit-key.pem|/home/runner/.ssh/peakfit-key.pem|g" ansible/inventory.ini
          cat ansible/inventory.ini

      - name: Attendre EC2 (30s)
        run: sleep 30

      - name: Lancer Ansible
        run: |
          ansible-playbook \
            -i ansible/inventory.ini \
            ansible/deploy.yml \
            --ssh-common-args='-o StrictHostKeyChecking=no'
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"

      - name: URL finale
        run: echo "🌐 http://peakfit-alb-1215627608.us-east-1.elb.amazonaws.com"
